language: node_js
node_js:
  - "4"
cache:
  directories:
  - node_modules
  - bower_components
addons:
  chrome: stable
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5 # give xvfb some time to start
  - make build
script:
  - hack/test-headless.sh test
  - hack/verify-dist.sh
